service: theodor-sdk-lambda-example

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  timeout: 30
  environment:
    THEODOR_API_KEY: ${env:THEODOR_API_KEY}

functions:
  analyzeHeartSound:
    handler: handler.analyzeHeartSound
    events:
      - http:
          path: analyze
          method: post
          cors: true
  
  fetchResults:
    handler: handler.fetchResults
    events:
      - http:
          path: results/{id}
          method: get
          cors: true