service: theodor-sdk-lambda-example

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  timeout: 30
  memorySize: 1024
  environment:
    THEODOR_API_KEY: ${env:THEODOR_API_KEY, 'your-api-key-placeholder'}

functions:
  analyse:
    handler: handler.analyse
    events:
      - http:
          path: analyze
          method: post
          cors: true
  
  fetchResults:
    handler: handler.fetchResults
    events:
      - http:
          path: results/{id}
          method: get
          cors: true